# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreferrer',
            unique_together=set([('user', 'campaign')]),
        ),
    ]
