# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import referral_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_module', '0003_auto_20171016_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferrerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('click', 'click')], db_index=True, default=referral_module.models.StatsType('click'), max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral_module.UserReferrer', verbose_name='stats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='bonus_policy',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=referral_module.models.default_bonus_policy),
        ),
    ]
